version: "3"
services:
  grpc-server-service:
    container_name: grpc-server
    build:
      context: ./server
      dockerfile: Dockerfile

  grpc-client-service:
    container_name: grpc-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
