apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grpc-client
spec:
  replicas: 2
  selector:
    matchLabels: 
      name: grpc-client
  template:
    metadata:
      name: grpc-client
      labels:
        name: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: sutanirojim/grpc-client-nodejs-example
          ports:
            - containerPort: 3000
